#!/usr/bin/env bash
# 04-bootstrap-flux.sh — Bootstraps FluxCD into the cluster
#
# GITHUB_TOKEN fix: exports the token as an environment variable before calling
# flux bootstrap. Without this, flux prompts interactively in the terminal
# even when the token is in .env.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
load_env "$ROOT_DIR/.env"

if [[ "${MM_BOT_DM_POLICY:-pairing}" == "open" ]]; then
  MM_BOT_ALLOW_FROM='["*"]'
else
  MM_BOT_ALLOW_FROM='[]'
fi
CLUSTER_PATH="clusters/${CLUSTER_NAME:-production}"

log_section "04 — Bootstrap FluxCD"
require_tool flux
require_tool kubectl
require_tool git

# Verify cluster is reachable
kubectl cluster-info &>/dev/null || {
  log_error "Cannot reach cluster. Run script 03 first."
  exit 1
}

# ── Render cluster-config.yaml ────────────────────────────────────────────────
log_step "Rendering cluster-config.yaml (Flux postBuild substitution values)"
mkdir -p "$ROOT_DIR/$CLUSTER_PATH"
cat > "$ROOT_DIR/$CLUSTER_PATH/cluster-config.yaml" << EOF
# AUTO-GENERATED by 04-bootstrap-flux.sh — safe to commit
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-values
  namespace: flux-system
data:
  DOMAIN: "${DOMAIN}"
  LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
  CLUSTER_NAME: "${CLUSTER_NAME}"
  S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
  AWS_REGION: "${AWS_REGION:-us-east-1}"
  SECRET_PREFIX: "${SECRET_PREFIX:-mattermost-openclaw-setup}"
  MM_BOT_DM_POLICY: "${MM_BOT_DM_POLICY:-pairing}"
EOF
log_ok "cluster-config.yaml rendered"

# ── Git setup ─────────────────────────────────────────────────────────────────
log_step "Setting up git"
cd "$ROOT_DIR"

if [[ ! -d ".git" ]]; then
  git init
  git remote add origin "https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git"
fi

# Set git identity (required for commits on fresh machines)
git config user.email 2>/dev/null || git config user.email "${LETSENCRYPT_EMAIL}"
git config user.name  2>/dev/null || git config user.name  "${GITHUB_USER}"

# Use authenticated remote URL for push — reset to unauthenticated after
git remote set-url origin \
  "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git"

git add clusters/ infrastructure/ apps/ terraform/ .gitignore .env.example README.md \
  bootstrap.sh teardown.sh Makefile scripts/ 2>/dev/null || true

git diff --cached --quiet || {
  git commit -m "feat: initial Mattermost GitOps deployment"
  git push -u origin "${GITHUB_BRANCH}"
  log_ok "Initial commit pushed"
}

# Reset to unauthenticated URL (token only needed for the push above)
git remote set-url origin \
  "https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git"

# ── Flux bootstrap ─────────────────────────────────────────────────────────────
log_step "Running flux bootstrap — this pushes FluxCD components to your repo"
echo "    Repo: https://github.com/${GITHUB_USER}/${GITHUB_REPO}"
echo "    Path: ${CLUSTER_PATH}"
echo ""

# CRITICAL: export GITHUB_TOKEN so flux picks it up without prompting
export GITHUB_TOKEN="${GITHUB_TOKEN}"

flux bootstrap github \
  --owner="${GITHUB_USER}" \
  --repository="${GITHUB_REPO}" \
  --branch="${GITHUB_BRANCH}" \
  --path="${CLUSTER_PATH}" \
  --personal \
  --token-auth

log_ok "Flux bootstrapped"

# Pull the gotk-components.yaml that flux pushed
git pull --rebase origin "${GITHUB_BRANCH}" 2>/dev/null || true

# Apply cluster-values ConfigMap immediately so Flux substitutions work from first reconcile
log_step "Applying cluster-values ConfigMap"
kubectl apply -f "$ROOT_DIR/$CLUSTER_PATH/cluster-config.yaml"
log_ok "cluster-values ConfigMap applied"

log_section "04 Complete"
echo "  FluxCD is now watching: https://github.com/${GITHUB_USER}/${GITHUB_REPO}"
echo "  Infrastructure will reconcile in the background."
echo "  Watch: flux get kustomizations -A --watch"
